[package]

name = "geohash"
version = "0.7.0"
authors = [ "Ning Sun <sunng@about.me>" ]
description = "Geohash implementation for Rust."
license = "MIT/Apache-2.0"
keywords = ["geohash", "gis", "geography"]
repository = "https://github.com/georust/geohash.rs"
readme = "README.md"
documentation = "https://georust.github.io/rust-geohash/"

[dependencies]
geo-types = "0.1"

[dev-dependencies]
num-traits = "0.2"
