[package]

name = "geohash"
version = "0.2.7-pre"
authors = [ "Ning Sun <sunng@about.me>" ]
description = "Geohash implementation for Rust."
license = "MIT/Apache-2.0"
keywords = ["geohash", "gis", "geography"]
repository = "https://github.com/georust/geohash.rs"
readme = "README.md"
documentation = "https://georust.github.io/rust-geohash/"

[dependencies]

geo = "^0.0.5"

[dev-dependencies]
num = "0.1.30"
