[package]

name = "geohash"
version = "0.8.0"
authors = [ "Ning Sun <sunng@about.me>" ]
description = "Geohash implementation for Rust."
license = "MIT/Apache-2.0"
keywords = ["geohash", "gis", "geography"]
repository = "https://github.com/georust/geohash.rs"
readme = "README.md"
documentation = "https://docs.rs/geohash/"

[dependencies]
geo-types = "0.2"
failure = "0.1.2"

[dev-dependencies]
num-traits = "0.2"
